In [1]:
import numpy as np
import pyximport
pyximport.install(setup_args = {"include_dirs":np.get_include()})

(None, <pyximport._pyximport3.PyxImportMetaFinder at 0x105a12a20>)

In [2]:

import cyth_test


In [2]:
numbers = 500.0 * np.random.rand(100000)


In [4]:
timeit(cyth_test.calculate_roots(numbers))

32.8 μs ± 96.3 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
grid = np.arange(16.0).reshape(4,4)
grid

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [10]:
cyth_test.get_order(grid, 4)

np.float64(0.2660379480841587)

In [2]:
import LebwohlLasher_cython

/Users/sebparkin/miniconda3/lib/python3.12/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /Users/sebparkin/Documents/University/Software Engineering and HPC/Project1/cython_tests/LebwohlLasher_cython.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
        # Now apply the Monte Carlo test - compare
        # exp( -(E_new - E_old) / T* ) >= rand(0,1)
            boltz = np.exp( -(en1 - en0) / Ts )

            if boltz >= np.random.uniform(0.0,1.0):
                accept += 1
                ^
------------------------------------------------------------

LebwohlLasher_cython.pyx:274:16: local variable 'accept' referenced before assignment
performance hint: LebwohlLasher_cython.pyx:259:20: Index should be typed for more efficient access
performance hint: Lebwoh

ImportError: Building module LebwohlLasher_cython failed: ['Cython.Compiler.Errors.CompileError: /Users/sebparkin/Documents/University/Software Engineering and HPC/Project1/cython_tests/LebwohlLasher_cython.pyx\n']

In [3]:
LebwohlLasher_cython.main('LebwohlLasher_cython', 50, 50, 0.5, 0)

LebwohlLasher_cython: Size: 50, Steps: 50, T*: 0.500: Order: 0.478, Time: 1.036362 s


In [6]:
grid = np.mgrid[0:5,0:5].reshape(2,-1).T

In [7]:
len(grid)

25

In [1]:
import energy_test

In [2]:
energy_test.main()

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
18.749835968017578 0.25471858516172086 0.8799999952316284
[[ 0.          1.          1.27106332  1.86852696  3.49839993]
 [ 5.11500928  5.58379631  7.          9.06244924  9.69893443]
 [10.         11.10506368 12.         13.         12.84638975]
 [15.         15.71431176 17.         18.         19.17421656]
 [20.         21.50517465 20.92548277 24.1710711  24.        ]]


In [1]:
import LL_cython

In [2]:
LL_cython.main('LL_cython', 50, 50, 0.5, 0)

LL_cython: Size: 50, Steps: 50, T*: 0.500: Order: 0.307, Time: 0.023805 s
